### ISSUE TITLE
ACTION: identify process for inventory optimization

### ISSUE THREAD

**Issue by Maria-Bruno** [stern-devops-2020-inventory/inventory#12]

**Comment by npd271** [comment]
Nora

**Comment by npd271** [comment]
**As an** Inventory Manager
**I need** to identify the right mechanism to ensure inventory optimization 
**So that** inventory levels are always sufficient to meet demand and limit costs

**Assumptions:**
- Input material levels must be maintained for finished goods production, and finished goods must be maintained to meet expected demand 
- Inventory Managers should systematically be kept aware of inventory levels

**Acceptance Criteria:**
```
- Given a Product ID with low-level inventory
- When a GET request is made
- Then a service alert will notify the inventory manager to reorder
```
