### ISSUE TITLE
ACTION: Confirm Product ID format from product team

### ISSUE THREAD

**Issue by Maria-Bruno** [stern-devops-2020-inventory/inventory#3]

**Comment by npd271** [comment]
Nora

**Comment by npd271** [comment]
**As a** Developer
**I need** to ensure that Product ID in inventory is aligned with Product ID in product
**So that** when a customer places an order, the product is identified with the same unique ID

**Assumptions:**
- Product ID should be unique for each product type (including size, color, make, etc.)
- Product ID should be persistent throughout the inventory lifecycle

**Acceptance Criteria:**
```
- Given a post to inventory from product
- When an update is made, the Product ID is checked for consistency (to SKU format)
- Then the Product ID will be stored in inventory
```

**Comment by Maria-Bruno** [comment]
![image.png](https://images.zenhubusercontent.com/5e55a7fc18544155cb048153/027e8ba9-ac4c-44ea-a624-a9707d7a724f)

Per Product team's Github, the product ID is an integer

**Comment by Maria-Bruno** [comment]
According to the screenshot, we are using the same format for Product IDs. No updates needed so I will move this issue to Closed.

**Comment by azelenovsky** [comment]
So the only issue here is that the Id's are primary keys inside the respective databases and they will not match.
