### ISSUE TITLE
Integrate Travis CI

### ISSUE THREAD

**Issue by Maria-Bruno** [stern-devops-2020-inventory/inventory#42]
**As a** developer
**I need** to use Travis CI with Redis for continuous integration
**So that** I can run nosetests automatically

**Assumptions:** 
*the instructions to mirror the repo from lab-flask-rest are correct and will meet our needs

**Acceptance Criteria:**
```
Given when I run nostests after adding new code
When I push code
Then travis CI will run these tests automatically
```

**Comment by azelenovsky** [comment]
Create a free account on Travis CI (travis-ci.com) for your GitHub organization. Andrey
Create a .travis.yml file and configure Travis CI to run test cases every time someone pushes to the master branch or submits a Pull Request.
Set up Travis CI to monitor your GitHub repository for push and pull requests.
Add a Travis CI badge to your README.md file so that everyone will know if the build is broken.
